### PR TITLE
Remove filter for VR device (3dRudder)

### PR DESCRIPTION
**Pull request by Mvivant**
I have one question:
* Is it possible to remove the ray on proxy? Because I have created a proxy for the 3dRudder device but the proxy created a ray and for the foot-controller it doesn't make sense. It's just a proxy for device that used a locomotion tool.

### CODE REVIEW

**Comment by amirebrahimi** [comment]
One idea is that you could add a default tool for the device that makes use of IRayVisibilitySettings to turn off the ray.

**Comment by Mvivant** [comment]
@amirebrahimi Thanks! it works 👍 

I don't know how get access for user to my speed settings (Vector3) in VR ? in a menu or something like that? Is it possible ?

**Comment by amirebrahimi** [comment]
You may be able to use https://github.com/Unity-Technologies/EditorVR/blob/development/Scripts/Interfaces/ISettingsMenuItemProvider.cs. Take a look at other tools that make use of it.

**Comment by Mvivant** [comment]
Thanks but I have the last version of XEditor 0.1.1 and Unity 2017.2.0p2 and the text doesn't appear on settings menu I have a missing monoScript on all Text, I delete all package and re-import but the issue is still here

**Comment by Mvivant** [comment]
Hi, 
How can add Reviewers or Assignees ?

**Comment by AndrewTHEManeri** [comment]
I'm not sure you have permission to do that, I've gone ahead and done it

**Comment by Mvivant** [comment]
Hi,

Someone can take a look on this PR ?
Thanks!

**Pull request closed without merging**
